import { MdModeEdit } from "react-icons/md";// assuming ProfileDropdown is a separate component

const userData = [
  {
    name: "John Doe",
    phone: "1234567890",
    profile: "Admin",
    email: "jdoe@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button className="p-2 rounded-lg bg-blue-400" onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Jane Smith",
    phone: "0987654321",
    profile: "Admin",
    email: "jsmith@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Himanshu Bachchan",
    phone: "1122334455",
    profile: "Admin",
    email: "mjohnson@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Emily Davis",
    phone: "6677889900",
    profile: "Admin",
    email: "edavis@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Sarah Brown",
    phone: "2233445566",
    profile: "Admin",
    email: "sbrown@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "David Wilson",
    phone: "4455667788",
    profile: "Admin",
    email: "dwilson@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "James Miller",
    phone: "5566778899",
    profile: "Admin",
    email: "jmiller@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Olivia Moore",
    phone: "6677889900",
    profile: "Admin",
    email: "omoore@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Liam Taylor",
    phone: "7788990011",
    profile: "Admin",
    email: "ltaylor@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Sophia Anderson",
    phone: "8899001122",
    profile: "Admin",
    email: "sanderson@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Mason Thomas",
    phone: "9900112233",
    profile: "Admin",
    email: "mthomas@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Isabella Jackson",
    phone: "2233445566",
    profile: "Admin",
    email: "ijackson@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Ethan White",
    phone: "3344556677",
    profile: "Admin",
    email: "ewhite@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Ava Harris",
    phone: "4455667788",
    profile: "Admin",
    email: "aharris@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Charlotte Clark",
    phone: "5566778899",
    profile: "Admin",
    email: "cclark@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Lucas Lewis",
    phone: "6677889900",
    profile: "Admin",
    email: "llewis@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Amelia Walker",
    phone: "7788990011",
    profile: "Admin",
    email: "awalker@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Benjamin Young",
    phone: "8899001122",
    profile: "Admin",
    email: "byoung@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Mia King",
    phone: "9900112233",
    profile: "Admin",
    email: "mking@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Henry Scott",
    phone: "2233445566",
    profile: "Admin",
    email: "hscott@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Alexander Green",
    phone: "3344556677",
    profile: "Admin",
    email: "agreen@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Zoe Adams",
    phone: "4455667788",
    profile: "admin",
    email: "zadams@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Jack Nelson",
    phone: "5566778899",
    profile: "Admin",
    email: "jnelson@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Scarlett Baker",
    phone: "6677889900",
    profile: "Admin",
    email: "sbaker@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Daniel Carter",
    phone: "7788990011",
    profile: "Admin",
    email: "dcarter@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Lily Perez",
    phone: "8899001122",
    profile: "Admin",
    email: "lperez@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "David Mitchell",
    profile: "Admin",
    email: "dmitchell@me.com",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    name: "Victoria Roberts",
    phone: "2233445566",
    profile: "Admin",
    email: "vroberts@me.com",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
];

const destData = [
  {
    destination: "Bali",
    currency: "IDR",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button className="mx-auto" onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Paris",
    currency: "EUR",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "London",
    currency: "GBP",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Tokyo",
    currency: "JPY",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button className="w-full align-center" onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Sydney",
    currency: "AUD",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Rome",
    currency: "EUR",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "New York",
    currency: "USD",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Dubai",
    currency: "AED",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Singapore",
    currency: "SGD",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Beijing",
    currency: "CNY",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Sydney",
    currency: "AUD",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    destination: "Tokyo",
    currency: "JPY",
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
];

const agentData = [
  {
    agentName: "Agent 1",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 2",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 3",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 4",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 5",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 6",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 7",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 8",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 9",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 10",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 11",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 12",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 13",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    agentName: "Agent 14",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
];

const supplierData = [
  {
    supplierName: "Supplier 1",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 2",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 3",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 4",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 5",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 6",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 7",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 8",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 9",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 10",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 11",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 12",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 13",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 14",
    status: <button className="p-2 rounded-lg bg-red-400"></button>, 
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  },
  {
    supplierName: "Supplier 15",
    status: <button className="p-2 rounded-lg bg-green-400"></button>,
    action: <button onClick={() => alert("Edit")}><MdModeEdit /></button>,
  }
];

const bookings = [
  {
    bookingId: "BKG001",
    destination: "Bali",
    bookingDate: "2024-10-01",
    salesSPOC: "John Doe",
    agentDetails: "Agent 1",
    customerName: "Alice Smith 2A / 1C",
    arrivalDate: "2024-11-01",
    departureDate: "2024-11-10",
    travelMonth: "November",
    countryCode: "+1",
    orderValue: "3000 USD",
    whatsappNumber: "1234567890",
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG002",
    destination: "Bali",
    bookingDate: "2024-10-01",
    salesSPOC: "John Doe",
    agentDetails: "Agent 1",
    customerName: "Alice Smith 2A / 1C",
    arrivalDate: "2024-11-01",
    departureDate: "2024-11-10",
    travelMonth: "November",
    countryCode: "+1",
    orderValue: "3000 USD",
    whatsappNumber: "1234567890",
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  // Add additional bookings up to BKG025
  // Repeat the same structure for the next 16 objects
];

export { bookings };
export { destData };
export { userData };
export { agentData };
export { supplierData };
