import { ProfileDropdown } from "../components/dropDown/DropDown"; // assuming ProfileDropdown is a separate component

const userData = [
  {
    name: "John Doe",
    phone: "1234567890",
    profile: <ProfileDropdown />,
    email: "jdoe@me.com",
    status: "Active",
    permissions: "View, Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Jane Smith",
    phone: "0987654321",
    profile: <ProfileDropdown />,
    email: "jsmith@me.com",
    status: "Active",
    permissions: "View, Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Michael Johnson",
    phone: "1122334455",
    profile: <ProfileDropdown />,
    email: "mjohnson@me.com",
    status: "Inactive",
    permissions: "View",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Emily Davis",
    phone: "6677889900",
    profile: <ProfileDropdown />,
    email: "edavis@me.com",
    status: "Active",
    permissions: "View, Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Sarah Brown",
    phone: "2233445566",
    profile: <ProfileDropdown />,
    email: "sbrown@me.com",
    status: "Active",
    permissions: "Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "David Wilson",
    phone: "4455667788",
    profile: <ProfileDropdown />,
    email: "dwilson@me.com",
    status: "Inactive",
    permissions: "View",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "James Miller",
    phone: "5566778899",
    profile: <ProfileDropdown />,
    email: "jmiller@me.com",
    status: "Active",
    permissions: "View, Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Olivia Moore",
    phone: "6677889900",
    profile: <ProfileDropdown />,
    email: "omoore@me.com",
    status: "Active",
    permissions: "View, Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Liam Taylor",
    phone: "7788990011",
    profile: <ProfileDropdown />,
    email: "ltaylor@me.com",
    status: "Inactive",
    permissions: "View, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Sophia Anderson",
    phone: "8899001122",
    profile: <ProfileDropdown />,
    email: "sanderson@me.com",
    status: "Active",
    permissions: "Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Mason Thomas",
    phone: "9900112233",
    profile: <ProfileDropdown />,
    email: "mthomas@me.com",
    status: "Active",
    permissions: "View",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Isabella Jackson",
    phone: "2233445566",
    profile: <ProfileDropdown />,
    email: "ijackson@me.com",
    status: "Active",
    permissions: "View, Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Ethan White",
    phone: "3344556677",
    profile: <ProfileDropdown />,
    email: "ewhite@me.com",
    status: "Inactive",
    permissions: "Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Ava Harris",
    phone: "4455667788",
    profile: <ProfileDropdown />,
    email: "aharris@me.com",
    status: "Active",
    permissions: "View, Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Charlotte Clark",
    phone: "5566778899",
    profile: <ProfileDropdown />,
    email: "cclark@me.com",
    status: "Inactive",
    permissions: "Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Lucas Lewis",
    phone: "6677889900",
    profile: <ProfileDropdown />,
    email: "llewis@me.com",
    status: "Active",
    permissions: "View, Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Amelia Walker",
    phone: "7788990011",
    profile: <ProfileDropdown />,
    email: "awalker@me.com",
    status: "Inactive",
    permissions: "View",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Benjamin Young",
    phone: "8899001122",
    profile: <ProfileDropdown />,
    email: "byoung@me.com",
    status: "Active",
    permissions: "Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Mia King",
    phone: "9900112233",
    profile: <ProfileDropdown />,
    email: "mking@me.com",
    status: "Inactive",
    permissions: "View, Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Henry Scott",
    phone: "2233445566",
    profile: <ProfileDropdown />,
    email: "hscott@me.com",
    status: "Active",
    permissions: "View, Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Alexander Green",
    phone: "3344556677",
    profile: <ProfileDropdown />,
    email: "agreen@me.com",
    status: "Active",
    permissions: "Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Zoe Adams",
    phone: "4455667788",
    profile: <ProfileDropdown />,
    email: "zadams@me.com",
    status: "Inactive",
    permissions: "Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Jack Nelson",
    phone: "5566778899",
    profile: <ProfileDropdown />,
    email: "jnelson@me.com",
    status: "Active",
    permissions: "View, Edit, Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Scarlett Baker",
    phone: "6677889900",
    profile: <ProfileDropdown />,
    email: "sbaker@me.com",
    status: "Active",
    permissions: "View",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Daniel Carter",
    phone: "7788990011",
    profile: <ProfileDropdown />,
    email: "dcarter@me.com",
    status: "Inactive",
    permissions: "Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Lily Perez",
    phone: "8899001122",
    profile: <ProfileDropdown />,
    email: "lperez@me.com",
    status: "Active",
    permissions: "View, Edit",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "David Mitchell",
    phone: "9900112233",
    profile: <ProfileDropdown />,
    email: "dmitchell@me.com",
    status: "Active",
    permissions: "Delete",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    name: "Victoria Roberts",
    phone: "2233445566",
    profile: <ProfileDropdown />,
    email: "vroberts@me.com",
    status: "Inactive",
    permissions: "View",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
];

const destData = [
  {
    destination: "Bali",
    currency: "IDR",
    agent: "Agent 1",
    supplier: "Supplier 1",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Paris",
    currency: "EUR",
    agent: "Agent 2",
    supplier: "Supplier 2",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Tokyo",
    currency: "JPY",
    agent: "Agent 3",
    supplier: "Supplier 3",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "New York",
    currency: "USD",
    agent: "Agent 4",
    supplier: "Supplier 4",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Sydney",
    currency: "AUD",
    agent: "Agent 5",
    supplier: "Supplier 5",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "London",
    currency: "GBP",
    agent: "Agent 6",
    supplier: "Supplier 6",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Rome",
    currency: "EUR",
    agent: "Agent 7",
    supplier: "Supplier 7",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Dubai",
    currency: "AED",
    agent: "Agent 8",
    supplier: "Supplier 8",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Maldives",
    currency: "MVR",
    agent: "Agent 9",
    supplier: "Supplier 9",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Amsterdam",
    currency: "EUR",
    agent: "Agent 10",
    supplier: "Supplier 10",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Istanbul",
    currency: "TRY",
    agent: "Agent 11",
    supplier: "Supplier 11",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Singapore",
    currency: "SGD",
    agent: "Agent 12",
    supplier: "Supplier 12",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Barcelona",
    currency: "EUR",
    agent: "Agent 13",
    supplier: "Supplier 13",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Los Angeles",
    currency: "USD",
    agent: "Agent 14",
    supplier: "Supplier 14",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Cairo",
    currency: "EGP",
    agent: "Agent 15",
    supplier: "Supplier 15",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Bangkok",
    currency: "THB",
    agent: "Agent 16",
    supplier: "Supplier 16",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Moscow",
    currency: "RUB",
    agent: "Agent 17",
    supplier: "Supplier 17",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Prague",
    currency: "CZK",
    agent: "Agent 18",
    supplier: "Supplier 18",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Cape Town",
    currency: "ZAR",
    agent: "Agent 19",
    supplier: "Supplier 19",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Berlin",
    currency: "EUR",
    agent: "Agent 20",
    supplier: "Supplier 20",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Seoul",
    currency: "KRW",
    agent: "Agent 21",
    supplier: "Supplier 21",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Vienna",
    currency: "EUR",
    agent: "Agent 22",
    supplier: "Supplier 22",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Lisbon",
    currency: "EUR",
    agent: "Agent 23",
    supplier: "Supplier 23",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Buenos Aires",
    currency: "ARS",
    agent: "Agent 24",
    supplier: "Supplier 24",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Oslo",
    currency: "NOK",
    agent: "Agent 25",
    supplier: "Supplier 25",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Madrid",
    currency: "EUR",
    agent: "Agent 26",
    supplier: "Supplier 26",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Hong Kong",
    currency: "HKD",
    agent: "Agent 27",
    supplier: "Supplier 27",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Zurich",
    currency: "CHF",
    agent: "Agent 28",
    supplier: "Supplier 28",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Athens",
    currency: "EUR",
    agent: "Agent 29",
    supplier: "Supplier 29",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Kuala Lumpur",
    currency: "MYR",
    agent: "Agent 30",
    supplier: "Supplier 30",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Mexico City",
    currency: "MXN",
    agent: "Agent 31",
    supplier: "Supplier 31",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
  {
    destination: "Lagos",
    currency: "NGN",
    agent: "Agent 32",
    supplier: "Supplier 32",
    status: "Active",
    action: <button onClick={() => alert("Edit")}>Edit</button>,
  },
];

const bookings = [
  {
    bookingId: "BKG001",
    destination: "Bali",
    bookingDate: "2024-10-01",
    salesSPOC: "John Doe",
    agentDetails: "Agent 1",
    customerName: "Alice Smith",
    numOfPax: "2A / 1C",
    arrivalDate: "2024-11-01",
    departureDate: "2024-11-10",
    travelMonth: "November",
    countryCode: "+1",
    orderValue: "3000 USD",
    whatsappNumber: "1234567890",
    bookingDocuments: [
      "Airticket",
      "Passport",
      "PAN",
      "Hotel Voucher",
      "Others",
    ],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG002",
    destination: "Paris",
    bookingDate: "2024-10-02",
    salesSPOC: "Jane Smith",
    agentDetails: "Agent 2",
    customerName: "Bob Johnson",
    numOfPax: "2A",
    arrivalDate: "2024-12-01",
    departureDate: "2024-12-10",
    travelMonth: "December",
    countryCode: "+44",
    orderValue: "4500 USD",
    whatsappNumber: "0987654321",
    bookingDocuments: ["Airticket", "Passport", "Hotel Voucher"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG003",
    destination: "London",
    bookingDate: "2024-10-03",
    salesSPOC: "Alice Williams",
    agentDetails: "Agent 3",
    customerName: "Charlie Brown",
    numOfPax: "1A",
    arrivalDate: "2024-10-15",
    departureDate: "2024-10-25",
    travelMonth: "October",
    countryCode: "+33",
    orderValue: "2500 USD",
    whatsappNumber: "1122334455",
    bookingDocuments: ["Airticket", "PAN", "Hotel Voucher"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG004",
    destination: "Tokyo",
    bookingDate: "2024-10-05",
    salesSPOC: "David Lee",
    agentDetails: "Agent 4",
    customerName: "Eve Adams",
    numOfPax: "2A / 2C",
    arrivalDate: "2024-11-20",
    departureDate: "2024-11-30",
    travelMonth: "November",
    countryCode: "+81",
    orderValue: "6000 USD",
    whatsappNumber: "6677889900",
    bookingDocuments: ["Airticket", "Passport", "PAN", "Hotel Voucher"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG005",
    destination: "Rome",
    bookingDate: "2024-10-06",
    salesSPOC: "Michael Scott",
    agentDetails: "Agent 5",
    customerName: "Pam Beesly",
    numOfPax: "1A / 1C",
    arrivalDate: "2024-12-05",
    departureDate: "2024-12-15",
    travelMonth: "December",
    countryCode: "+39",
    orderValue: "4000 USD",
    whatsappNumber: "2233445566",
    bookingDocuments: ["Airticket", "Passport", "Hotel Voucher"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG006",
    destination: "New York",
    bookingDate: "2024-10-07",
    salesSPOC: "Dwight Schrute",
    agentDetails: "Agent 6",
    customerName: "Ryan Howard",
    numOfPax: "2A",
    arrivalDate: "2024-11-12",
    departureDate: "2024-11-22",
    travelMonth: "November",
    countryCode: "+1",
    orderValue: "5000 USD",
    whatsappNumber: "3344556677",
    bookingDocuments: ["Airticket", "PAN", "Hotel Voucher", "Others"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG007",
    destination: "Dubai",
    bookingDate: "2024-10-08",
    salesSPOC: "Jim Halpert",
    agentDetails: "Agent 7",
    customerName: "Angela Martin",
    numOfPax: "1A / 1C",
    arrivalDate: "2024-10-20",
    departureDate: "2024-10-30",
    travelMonth: "October",
    countryCode: "+971",
    orderValue: "3500 USD",
    whatsappNumber: "5566778899",
    bookingDocuments: ["Airticket", "Passport", "PAN"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG008",
    destination: "Singapore",
    bookingDate: "2024-10-09",
    salesSPOC: "Oscar Martinez",
    agentDetails: "Agent 8",
    customerName: "Stanley Hudson",
    numOfPax: "2A",
    arrivalDate: "2024-11-10",
    departureDate: "2024-11-20",
    travelMonth: "November",
    countryCode: "+65",
    orderValue: "5500 USD",
    whatsappNumber: "6677889900",
    bookingDocuments: ["Airticket", "Hotel Voucher"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  {
    bookingId: "BKG009",
    destination: "Sydney",
    bookingDate: "2024-10-10",
    salesSPOC: "Kelly Kapoor",
    agentDetails: "Agent 9",
    customerName: "Meredith Palmer",
    numOfPax: "1A",
    arrivalDate: "2024-12-01",
    departureDate: "2024-12-10",
    travelMonth: "December",
    countryCode: "+61",
    orderValue: "4200 USD",
    whatsappNumber: "2233445566",
    bookingDocuments: ["Airticket", "Passport", "Hotel Voucher", "Others"],
    bookingSheets: ["Sales Sheet", "Email Confirmation"],
    action: <button onClick={() => alert("View/Manage")}>View/Manage</button>,
  },
  // Add additional bookings up to BKG025
  // Repeat the same structure for the next 16 objects
];

export { bookings };
export { destData };
export { userData };
