import { createSlice } from '@reduxjs/toolkit';

// Define your initial state
const initialState = {
  value: 0,  // Example initial state
};

// Create your slice
const vendorSlice = createSlice({
  name: 'vendorSlice',  // This is the name of the slice
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1;  // Mutating the state directly is fine with Redux Toolkit
    },
    decrement: (state) => {
      state.value -= 1;
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement } = yourSlice.actions;

// Export the reducer to be used in the store
export default yourSlice.reducer;
